### ISSUE TITLE
KeyError: PRSJMJ in apr20pub.dat file

### ISSUE THREAD

**Issue by danbruen85** [bdecon/econ_data#247]
Hi Brian,
I get Keyerror: 'PRSJMJ' in the apr20pub.dat file. I rename the 2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt
to January_2020_Record_Layout.txt file and use it as the dictionary for 2020. Using the 2017 dictionary also gives the same error.
PRSJMS is the variable in the 2020 dictionary. After including this in the VarList in bd_CPS_details, it is still not being captured in the following lines of bd_CPS_dd:
        d = {text_repl(s[0]): [int(s[3])-1, int(s[4]), int(s[2])] 
             for s in re.findall(dvals['re'], ddf)}

**Comment by bdecon** [comment]
Hi Dan,

I think this was fixed when I pushed my local version this weekend. Because the definitions for PRSJMJ and PRSJMS are the same between 2017 and 2020, I added .replace('PRSJMS', 'PRSJMJ') to portion of bd_CPS_details.py that renames variables by replacing the name in the data dictionary.

**Comment by bdecon** [comment]
Nevermind, you are right, ignore my previous reply. I had manually edited the data dictionary file for 2020 because the format for the PRSJMS line is not correct in `2020_Basic_CPS_Public_Use_Record_Layout_plus_IO_Code_list.txt`. I'll need to find a solution that doesn't require that manual step.

**Comment by bdecon** [comment]
Added a section to the first codeblock in `bd_CPS_dd.ipynb` that takes the original 2020 data dictionary from Census and fixes the two typos and saves the new file as `January_2020_Record_Layout.txt`. This should fix the issue.
